### PR TITLE
Fix #172 groups not working and fix #181 cookie banner not detected

### LINKED ISSUE #172: This cancels users "/group/" in inputs.txt therefore breaks groups scraping
https://github.com/harismuneer/Ultimate-Facebook-Scraper/blob/4f54d8473d35b16f81ba5fbff7f112acc35c57bc/scraper/scraper.py#L798

### LINKED ISSUE #181: ERROR: The system was unable to find the specified registry key or value. There's some error in log in. <class 'TypeError'>
**Describe the bug**

**To Reproduce**
1. Configure '…'
2. Run '…'
3. …

**Expected behavior**

**Screenshots or command output**
If applicable, add screenshots or `output logs` to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Python version [e.g. 3.7.5]
 - Chrome web driver version [e.g 81]

**Additional context**

### PR DESCRIPTION
**Pull request by lesander**
Hi there,

Thought I'd contribute some of my fixes for UFS. I'm not 100% sure what the original `facebook_https_prefix + facebook_link_body + get_item_id(line)` was used for, but this broke https://www.facebook.com/groups/group_name urls, so I refactored it a bit.

This fixes issues #172 and #181 

Cheers.

### CODE REVIEW

**Comment by nvergnac** [comment]
Hey Lesander, Did you succeed to retrieve group posts with UFS ? I've been trying for a few days to scrape group post from a private FB group but I get nothing in the output txt file. Is it because it's a private group ? The credentials i'm using have access to this particular group.

**Comment by lesander** [comment]
Hi @nvergnac, I ended up writing my own scraper to scrape private groups. This repository doesn't seem to work for the new facebook layout (yet).

**Comment by nvergnac** [comment]
Hi @lesander, thanks for the answer, you managed to handle the new FB UI and scrape groups then ? Is it the repo you forked from UFS or is it private ?

**Comment by lesander** [comment]
Hi @nvergnac, It's a private repository for my work unfortunately. Will discuss internally if it can be made public. Seems especially relevant now since @harismuneer has taken his open source project behind a paywall.

**Comment by nvergnac** [comment]
Hi @lesander, Thanks for getting back to me. It would be great if you manage to make it public since UFS is not free anymore, that would be a great help !

**Comment by lesander** [comment]
Hi @nvergnac, I've published my code here: https://github.com/lesander/fbgs. Feel free to take it for a spin, feedback welcome 😄

**Pull request merged**
